// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: src/rpc/tsunagi.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tsunagi_DeliverMessage_FullMethodName = "/rpc.Tsunagi/DeliverMessage"
	Tsunagi_ForwardMessage_FullMethodName = "/rpc.Tsunagi/ForwardMessage"
)

// TsunagiClient is the client API for Tsunagi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TsunagiClient interface {
	DeliverMessage(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*Empty, error)
	ForwardMessage(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*Empty, error)
}

type tsunagiClient struct {
	cc grpc.ClientConnInterface
}

func NewTsunagiClient(cc grpc.ClientConnInterface) TsunagiClient {
	return &tsunagiClient{cc}
}

func (c *tsunagiClient) DeliverMessage(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Tsunagi_DeliverMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tsunagiClient) ForwardMessage(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Tsunagi_ForwardMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TsunagiServer is the server API for Tsunagi service.
// All implementations must embed UnimplementedTsunagiServer
// for forward compatibility.
type TsunagiServer interface {
	DeliverMessage(context.Context, *DeliverRequest) (*Empty, error)
	ForwardMessage(context.Context, *ForwardRequest) (*Empty, error)
	mustEmbedUnimplementedTsunagiServer()
}

// UnimplementedTsunagiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTsunagiServer struct{}

func (UnimplementedTsunagiServer) DeliverMessage(context.Context, *DeliverRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverMessage not implemented")
}
func (UnimplementedTsunagiServer) ForwardMessage(context.Context, *ForwardRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardMessage not implemented")
}
func (UnimplementedTsunagiServer) mustEmbedUnimplementedTsunagiServer() {}
func (UnimplementedTsunagiServer) testEmbeddedByValue()                 {}

// UnsafeTsunagiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TsunagiServer will
// result in compilation errors.
type UnsafeTsunagiServer interface {
	mustEmbedUnimplementedTsunagiServer()
}

func RegisterTsunagiServer(s grpc.ServiceRegistrar, srv TsunagiServer) {
	// If the following call panics, it indicates UnimplementedTsunagiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tsunagi_ServiceDesc, srv)
}

func _Tsunagi_DeliverMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsunagiServer).DeliverMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tsunagi_DeliverMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsunagiServer).DeliverMessage(ctx, req.(*DeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tsunagi_ForwardMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TsunagiServer).ForwardMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tsunagi_ForwardMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TsunagiServer).ForwardMessage(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tsunagi_ServiceDesc is the grpc.ServiceDesc for Tsunagi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tsunagi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Tsunagi",
	HandlerType: (*TsunagiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverMessage",
			Handler:    _Tsunagi_DeliverMessage_Handler,
		},
		{
			MethodName: "ForwardMessage",
			Handler:    _Tsunagi_ForwardMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/rpc/tsunagi.proto",
}
