// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: src/rpc/tsunagi.proto

package rpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Auth_GetChallenge_FullMethodName   = "/rpc.Auth/GetChallenge"
	Auth_ProveChallenge_FullMethodName = "/rpc.Auth/ProveChallenge"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	GetChallenge(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthChallenge, error)
	ProveChallenge(ctx context.Context, in *AuthProof, opts ...grpc.CallOption) (*AuthToken, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) GetChallenge(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthChallenge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthChallenge)
	err := c.cc.Invoke(ctx, Auth_GetChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ProveChallenge(ctx context.Context, in *AuthProof, opts ...grpc.CallOption) (*AuthToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthToken)
	err := c.cc.Invoke(ctx, Auth_ProveChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility.
type AuthServer interface {
	GetChallenge(context.Context, *AuthRequest) (*AuthChallenge, error)
	ProveChallenge(context.Context, *AuthProof) (*AuthToken, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServer struct{}

func (UnimplementedAuthServer) GetChallenge(context.Context, *AuthRequest) (*AuthChallenge, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChallenge not implemented")
}
func (UnimplementedAuthServer) ProveChallenge(context.Context, *AuthProof) (*AuthToken, error) {
	return nil, status.Error(codes.Unimplemented, "method ProveChallenge not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}
func (UnimplementedAuthServer) testEmbeddedByValue()              {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	// If the following call panics, it indicates UnimplementedAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_GetChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_GetChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetChallenge(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ProveChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ProveChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_ProveChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ProveChallenge(ctx, req.(*AuthProof))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChallenge",
			Handler:    _Auth_GetChallenge_Handler,
		},
		{
			MethodName: "ProveChallenge",
			Handler:    _Auth_ProveChallenge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/rpc/tsunagi.proto",
}

const (
	Tsunagi_ConnectRelay_FullMethodName  = "/rpc.Tsunagi/ConnectRelay"
	Tsunagi_ConnectClient_FullMethodName = "/rpc.Tsunagi/ConnectClient"
)

// TsunagiClient is the client API for Tsunagi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TsunagiClient interface {
	// ConnectRelay is for a relay to connect to another relay.
	// This should be used for relay message passing, since a relay never needs to recieve events.
	ConnectRelay(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, Empty], error)
	// ConnectClient is for a client to connect with a relay.
	// This should be used when the connecting client wants to also recieve events from the server.
	// If they only plan on pushing events, they should use ConnectRelay instead.
	ConnectClient(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, Event], error)
}

type tsunagiClient struct {
	cc grpc.ClientConnInterface
}

func NewTsunagiClient(cc grpc.ClientConnInterface) TsunagiClient {
	return &tsunagiClient{cc}
}

func (c *tsunagiClient) ConnectRelay(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tsunagi_ServiceDesc.Streams[0], Tsunagi_ConnectRelay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tsunagi_ConnectRelayClient = grpc.ClientStreamingClient[Event, Empty]

func (c *tsunagiClient) ConnectClient(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tsunagi_ServiceDesc.Streams[1], Tsunagi_ConnectClient_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, Event]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tsunagi_ConnectClientClient = grpc.BidiStreamingClient[Event, Event]

// TsunagiServer is the server API for Tsunagi service.
// All implementations must embed UnimplementedTsunagiServer
// for forward compatibility.
type TsunagiServer interface {
	// ConnectRelay is for a relay to connect to another relay.
	// This should be used for relay message passing, since a relay never needs to recieve events.
	ConnectRelay(grpc.ClientStreamingServer[Event, Empty]) error
	// ConnectClient is for a client to connect with a relay.
	// This should be used when the connecting client wants to also recieve events from the server.
	// If they only plan on pushing events, they should use ConnectRelay instead.
	ConnectClient(grpc.BidiStreamingServer[Event, Event]) error
	mustEmbedUnimplementedTsunagiServer()
}

// UnimplementedTsunagiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTsunagiServer struct{}

func (UnimplementedTsunagiServer) ConnectRelay(grpc.ClientStreamingServer[Event, Empty]) error {
	return status.Error(codes.Unimplemented, "method ConnectRelay not implemented")
}
func (UnimplementedTsunagiServer) ConnectClient(grpc.BidiStreamingServer[Event, Event]) error {
	return status.Error(codes.Unimplemented, "method ConnectClient not implemented")
}
func (UnimplementedTsunagiServer) mustEmbedUnimplementedTsunagiServer() {}
func (UnimplementedTsunagiServer) testEmbeddedByValue()                 {}

// UnsafeTsunagiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TsunagiServer will
// result in compilation errors.
type UnsafeTsunagiServer interface {
	mustEmbedUnimplementedTsunagiServer()
}

func RegisterTsunagiServer(s grpc.ServiceRegistrar, srv TsunagiServer) {
	// If the following call panics, it indicates UnimplementedTsunagiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tsunagi_ServiceDesc, srv)
}

func _Tsunagi_ConnectRelay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TsunagiServer).ConnectRelay(&grpc.GenericServerStream[Event, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tsunagi_ConnectRelayServer = grpc.ClientStreamingServer[Event, Empty]

func _Tsunagi_ConnectClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TsunagiServer).ConnectClient(&grpc.GenericServerStream[Event, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tsunagi_ConnectClientServer = grpc.BidiStreamingServer[Event, Event]

// Tsunagi_ServiceDesc is the grpc.ServiceDesc for Tsunagi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tsunagi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Tsunagi",
	HandlerType: (*TsunagiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectRelay",
			Handler:       _Tsunagi_ConnectRelay_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ConnectClient",
			Handler:       _Tsunagi_ConnectClient_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "src/rpc/tsunagi.proto",
}
