// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: src/rpc/tsunagi.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{0}
}

type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceID      []byte                 `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	RelayAddr     string                 `protobuf:"bytes,2,opt,name=RelayAddr,proto3" json:"RelayAddr,omitempty"`
	CipherText    []byte                 `protobuf:"bytes,3,opt,name=CipherText,proto3" json:"CipherText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardRequest) GetDeviceID() []byte {
	if x != nil {
		return x.DeviceID
	}
	return nil
}

func (x *ForwardRequest) GetRelayAddr() string {
	if x != nil {
		return x.RelayAddr
	}
	return ""
}

func (x *ForwardRequest) GetCipherText() []byte {
	if x != nil {
		return x.CipherText
	}
	return nil
}

type DeliverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceID      []byte                 `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	CipherText    []byte                 `protobuf:"bytes,2,opt,name=CipherText,proto3" json:"CipherText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverRequest) GetDeviceID() []byte {
	if x != nil {
		return x.DeviceID
	}
	return nil
}

func (x *DeliverRequest) GetCipherText() []byte {
	if x != nil {
		return x.CipherText
	}
	return nil
}

var File_src_rpc_tsunagi_proto protoreflect.FileDescriptor

const file_src_rpc_tsunagi_proto_rawDesc = "" +
	"\n" +
	"\x15src/rpc/tsunagi.proto\x12\x03rpc\"\a\n" +
	"\x05Empty\"j\n" +
	"\x0eForwardRequest\x12\x1a\n" +
	"\bDeviceID\x18\x01 \x01(\fR\bDeviceID\x12\x1c\n" +
	"\tRelayAddr\x18\x02 \x01(\tR\tRelayAddr\x12\x1e\n" +
	"\n" +
	"CipherText\x18\x03 \x01(\fR\n" +
	"CipherText\"L\n" +
	"\x0eDeliverRequest\x12\x1a\n" +
	"\bDeviceID\x18\x01 \x01(\fR\bDeviceID\x12\x1e\n" +
	"\n" +
	"CipherText\x18\x02 \x01(\fR\n" +
	"CipherText2s\n" +
	"\aTsunagi\x123\n" +
	"\x0eDeliverMessage\x12\x13.rpc.DeliverRequest\x1a\n" +
	".rpc.Empty\"\x00\x123\n" +
	"\x0eForwardMessage\x12\x13.rpc.ForwardRequest\x1a\n" +
	".rpc.Empty\"\x00B\x11Z\x0ftsunagi/src/rpcb\x06proto3"

var (
	file_src_rpc_tsunagi_proto_rawDescOnce sync.Once
	file_src_rpc_tsunagi_proto_rawDescData []byte
)

func file_src_rpc_tsunagi_proto_rawDescGZIP() []byte {
	file_src_rpc_tsunagi_proto_rawDescOnce.Do(func() {
		file_src_rpc_tsunagi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_rpc_tsunagi_proto_rawDesc), len(file_src_rpc_tsunagi_proto_rawDesc)))
	})
	return file_src_rpc_tsunagi_proto_rawDescData
}

var file_src_rpc_tsunagi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_rpc_tsunagi_proto_goTypes = []any{
	(*Empty)(nil),          // 0: rpc.Empty
	(*ForwardRequest)(nil), // 1: rpc.ForwardRequest
	(*DeliverRequest)(nil), // 2: rpc.DeliverRequest
}
var file_src_rpc_tsunagi_proto_depIdxs = []int32{
	2, // 0: rpc.Tsunagi.DeliverMessage:input_type -> rpc.DeliverRequest
	1, // 1: rpc.Tsunagi.ForwardMessage:input_type -> rpc.ForwardRequest
	0, // 2: rpc.Tsunagi.DeliverMessage:output_type -> rpc.Empty
	0, // 3: rpc.Tsunagi.ForwardMessage:output_type -> rpc.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_rpc_tsunagi_proto_init() }
func file_src_rpc_tsunagi_proto_init() {
	if File_src_rpc_tsunagi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_rpc_tsunagi_proto_rawDesc), len(file_src_rpc_tsunagi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_rpc_tsunagi_proto_goTypes,
		DependencyIndexes: file_src_rpc_tsunagi_proto_depIdxs,
		MessageInfos:      file_src_rpc_tsunagi_proto_msgTypes,
	}.Build()
	File_src_rpc_tsunagi_proto = out.File
	file_src_rpc_tsunagi_proto_goTypes = nil
	file_src_rpc_tsunagi_proto_depIdxs = nil
}
