// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: src/rpc/tsunagi.proto

package rpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthRequest is sent by a client who wants to authenticate.
// They will provide their identity and then wait to verify it.
type AuthRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceID         []byte                 `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`                 // 32 bytes
	PubKey           []byte                 `protobuf:"bytes,2,opt,name=PubKey,proto3" json:"PubKey,omitempty"`                     // public key
	HandshakeInitMsg []byte                 `protobuf:"bytes,3,opt,name=HandshakeInitMsg,proto3" json:"HandshakeInitMsg,omitempty"` // noise IN step 1 handshake msg
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetDeviceID() []byte {
	if x != nil {
		return x.DeviceID
	}
	return nil
}

func (x *AuthRequest) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *AuthRequest) GetHandshakeInitMsg() []byte {
	if x != nil {
		return x.HandshakeInitMsg
	}
	return nil
}

// AuthChallenge is sent by the server to a connecting client.
// They must solve it and provide a proof.
type AuthChallenge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HandshakeDoneMsg []byte                 `protobuf:"bytes,1,opt,name=HandshakeDoneMsg,proto3" json:"HandshakeDoneMsg,omitempty"` // noise IN step 2 handshake msg
	AuthChallenge    []byte                 `protobuf:"bytes,2,opt,name=AuthChallenge,proto3" json:"AuthChallenge,omitempty"`       // encrypted challenge
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthChallenge) Reset() {
	*x = AuthChallenge{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallenge) ProtoMessage() {}

func (x *AuthChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallenge.ProtoReflect.Descriptor instead.
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{1}
}

func (x *AuthChallenge) GetHandshakeDoneMsg() []byte {
	if x != nil {
		return x.HandshakeDoneMsg
	}
	return nil
}

func (x *AuthChallenge) GetAuthChallenge() []byte {
	if x != nil {
		return x.AuthChallenge
	}
	return nil
}

// AuthProof is the solved challenge.
type AuthProof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// signature of the nonce
	Signature     []byte `protobuf:"bytes,1,opt,name=Signature,proto3" json:"Signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthProof) Reset() {
	*x = AuthProof{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProof) ProtoMessage() {}

func (x *AuthProof) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProof.ProtoReflect.Descriptor instead.
func (*AuthProof) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{2}
}

func (x *AuthProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// AuthToken returns the token to authenticate with the Tsunagi service.
type AuthToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{3}
}

func (x *AuthToken) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{4}
}

type ClientEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DeviceID  []byte                 `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"` // 32 bytes
	RelayAddr string                 `protobuf:"bytes,2,opt,name=RelayAddr,proto3" json:"RelayAddr,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientEvent_NoiseHandshake
	//	*ClientEvent_MessagePayload
	Body          isClientEvent_Body `protobuf_oneof:"Body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{5}
}

func (x *ClientEvent) GetDeviceID() []byte {
	if x != nil {
		return x.DeviceID
	}
	return nil
}

func (x *ClientEvent) GetRelayAddr() string {
	if x != nil {
		return x.RelayAddr
	}
	return ""
}

func (x *ClientEvent) GetBody() isClientEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientEvent) GetNoiseHandshake() *NoiseHandshake {
	if x != nil {
		if x, ok := x.Body.(*ClientEvent_NoiseHandshake); ok {
			return x.NoiseHandshake
		}
	}
	return nil
}

func (x *ClientEvent) GetMessagePayload() *MessagePayload {
	if x != nil {
		if x, ok := x.Body.(*ClientEvent_MessagePayload); ok {
			return x.MessagePayload
		}
	}
	return nil
}

type isClientEvent_Body interface {
	isClientEvent_Body()
}

type ClientEvent_NoiseHandshake struct {
	NoiseHandshake *NoiseHandshake `protobuf:"bytes,3,opt,name=NoiseHandshake,proto3,oneof"`
}

type ClientEvent_MessagePayload struct {
	MessagePayload *MessagePayload `protobuf:"bytes,4,opt,name=MessagePayload,proto3,oneof"`
}

func (*ClientEvent_NoiseHandshake) isClientEvent_Body() {}

func (*ClientEvent_MessagePayload) isClientEvent_Body() {}

type RelayEvent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceID []byte                 `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"` // 32 bytes
	// Types that are valid to be assigned to Body:
	//
	//	*RelayEvent_NoiseHandshake
	//	*RelayEvent_MessagePayload
	Body          isRelayEvent_Body `protobuf_oneof:"Body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayEvent) Reset() {
	*x = RelayEvent{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayEvent) ProtoMessage() {}

func (x *RelayEvent) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayEvent.ProtoReflect.Descriptor instead.
func (*RelayEvent) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{6}
}

func (x *RelayEvent) GetDeviceID() []byte {
	if x != nil {
		return x.DeviceID
	}
	return nil
}

func (x *RelayEvent) GetBody() isRelayEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RelayEvent) GetNoiseHandshake() *NoiseHandshake {
	if x != nil {
		if x, ok := x.Body.(*RelayEvent_NoiseHandshake); ok {
			return x.NoiseHandshake
		}
	}
	return nil
}

func (x *RelayEvent) GetMessagePayload() *MessagePayload {
	if x != nil {
		if x, ok := x.Body.(*RelayEvent_MessagePayload); ok {
			return x.MessagePayload
		}
	}
	return nil
}

type isRelayEvent_Body interface {
	isRelayEvent_Body()
}

type RelayEvent_NoiseHandshake struct {
	NoiseHandshake *NoiseHandshake `protobuf:"bytes,2,opt,name=NoiseHandshake,proto3,oneof"`
}

type RelayEvent_MessagePayload struct {
	MessagePayload *MessagePayload `protobuf:"bytes,3,opt,name=MessagePayload,proto3,oneof"`
}

func (*RelayEvent_NoiseHandshake) isRelayEvent_Body() {}

func (*RelayEvent_MessagePayload) isRelayEvent_Body() {}

// noise message to continue handshake with a client
type NoiseHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         []byte                 `protobuf:"bytes,1,opt,name=State,proto3" json:"State,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoiseHandshake) Reset() {
	*x = NoiseHandshake{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoiseHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoiseHandshake) ProtoMessage() {}

func (x *NoiseHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoiseHandshake.ProtoReflect.Descriptor instead.
func (*NoiseHandshake) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{7}
}

func (x *NoiseHandshake) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

// encrypted message data for the recieving client
type MessagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CipherText    []byte                 `protobuf:"bytes,1,opt,name=CipherText,proto3" json:"CipherText,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePayload) Reset() {
	*x = MessagePayload{}
	mi := &file_src_rpc_tsunagi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePayload) ProtoMessage() {}

func (x *MessagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_src_rpc_tsunagi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePayload.ProtoReflect.Descriptor instead.
func (*MessagePayload) Descriptor() ([]byte, []int) {
	return file_src_rpc_tsunagi_proto_rawDescGZIP(), []int{8}
}

func (x *MessagePayload) GetCipherText() []byte {
	if x != nil {
		return x.CipherText
	}
	return nil
}

var File_src_rpc_tsunagi_proto protoreflect.FileDescriptor

const file_src_rpc_tsunagi_proto_rawDesc = "" +
	"\n" +
	"\x15src/rpc/tsunagi.proto\x12\x03rpc\"m\n" +
	"\vAuthRequest\x12\x1a\n" +
	"\bDeviceID\x18\x01 \x01(\fR\bDeviceID\x12\x16\n" +
	"\x06PubKey\x18\x02 \x01(\fR\x06PubKey\x12*\n" +
	"\x10HandshakeInitMsg\x18\x03 \x01(\fR\x10HandshakeInitMsg\"a\n" +
	"\rAuthChallenge\x12*\n" +
	"\x10HandshakeDoneMsg\x18\x01 \x01(\fR\x10HandshakeDoneMsg\x12$\n" +
	"\rAuthChallenge\x18\x02 \x01(\fR\rAuthChallenge\")\n" +
	"\tAuthProof\x12\x1c\n" +
	"\tSignature\x18\x01 \x01(\fR\tSignature\"!\n" +
	"\tAuthToken\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\fR\x05Token\"\a\n" +
	"\x05Empty\"\xcd\x01\n" +
	"\vClientEvent\x12\x1a\n" +
	"\bDeviceID\x18\x01 \x01(\fR\bDeviceID\x12\x1c\n" +
	"\tRelayAddr\x18\x02 \x01(\tR\tRelayAddr\x12=\n" +
	"\x0eNoiseHandshake\x18\x03 \x01(\v2\x13.rpc.NoiseHandshakeH\x00R\x0eNoiseHandshake\x12=\n" +
	"\x0eMessagePayload\x18\x04 \x01(\v2\x13.rpc.MessagePayloadH\x00R\x0eMessagePayloadB\x06\n" +
	"\x04Body\"\xae\x01\n" +
	"\n" +
	"RelayEvent\x12\x1a\n" +
	"\bDeviceID\x18\x01 \x01(\fR\bDeviceID\x12=\n" +
	"\x0eNoiseHandshake\x18\x02 \x01(\v2\x13.rpc.NoiseHandshakeH\x00R\x0eNoiseHandshake\x12=\n" +
	"\x0eMessagePayload\x18\x03 \x01(\v2\x13.rpc.MessagePayloadH\x00R\x0eMessagePayloadB\x06\n" +
	"\x04Body\"&\n" +
	"\x0eNoiseHandshake\x12\x14\n" +
	"\x05State\x18\x01 \x01(\fR\x05State\"0\n" +
	"\x0eMessagePayload\x12\x1e\n" +
	"\n" +
	"CipherText\x18\x01 \x01(\fR\n" +
	"CipherText2r\n" +
	"\x04Auth\x126\n" +
	"\fGetChallenge\x12\x10.rpc.AuthRequest\x1a\x12.rpc.AuthChallenge\"\x00\x122\n" +
	"\x0eProveChallenge\x12\x0e.rpc.AuthProof\x1a\x0e.rpc.AuthToken\"\x002t\n" +
	"\aTsunagi\x12/\n" +
	"\fConnectRelay\x12\x0f.rpc.RelayEvent\x1a\n" +
	".rpc.Empty\"\x00(\x01\x128\n" +
	"\rConnectClient\x12\x10.rpc.ClientEvent\x1a\x0f.rpc.RelayEvent\"\x00(\x010\x01B\x11Z\x0ftsunagi/src/rpcb\x06proto3"

var (
	file_src_rpc_tsunagi_proto_rawDescOnce sync.Once
	file_src_rpc_tsunagi_proto_rawDescData []byte
)

func file_src_rpc_tsunagi_proto_rawDescGZIP() []byte {
	file_src_rpc_tsunagi_proto_rawDescOnce.Do(func() {
		file_src_rpc_tsunagi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_rpc_tsunagi_proto_rawDesc), len(file_src_rpc_tsunagi_proto_rawDesc)))
	})
	return file_src_rpc_tsunagi_proto_rawDescData
}

var file_src_rpc_tsunagi_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_src_rpc_tsunagi_proto_goTypes = []any{
	(*AuthRequest)(nil),    // 0: rpc.AuthRequest
	(*AuthChallenge)(nil),  // 1: rpc.AuthChallenge
	(*AuthProof)(nil),      // 2: rpc.AuthProof
	(*AuthToken)(nil),      // 3: rpc.AuthToken
	(*Empty)(nil),          // 4: rpc.Empty
	(*ClientEvent)(nil),    // 5: rpc.ClientEvent
	(*RelayEvent)(nil),     // 6: rpc.RelayEvent
	(*NoiseHandshake)(nil), // 7: rpc.NoiseHandshake
	(*MessagePayload)(nil), // 8: rpc.MessagePayload
}
var file_src_rpc_tsunagi_proto_depIdxs = []int32{
	7, // 0: rpc.ClientEvent.NoiseHandshake:type_name -> rpc.NoiseHandshake
	8, // 1: rpc.ClientEvent.MessagePayload:type_name -> rpc.MessagePayload
	7, // 2: rpc.RelayEvent.NoiseHandshake:type_name -> rpc.NoiseHandshake
	8, // 3: rpc.RelayEvent.MessagePayload:type_name -> rpc.MessagePayload
	0, // 4: rpc.Auth.GetChallenge:input_type -> rpc.AuthRequest
	2, // 5: rpc.Auth.ProveChallenge:input_type -> rpc.AuthProof
	6, // 6: rpc.Tsunagi.ConnectRelay:input_type -> rpc.RelayEvent
	5, // 7: rpc.Tsunagi.ConnectClient:input_type -> rpc.ClientEvent
	1, // 8: rpc.Auth.GetChallenge:output_type -> rpc.AuthChallenge
	3, // 9: rpc.Auth.ProveChallenge:output_type -> rpc.AuthToken
	4, // 10: rpc.Tsunagi.ConnectRelay:output_type -> rpc.Empty
	6, // 11: rpc.Tsunagi.ConnectClient:output_type -> rpc.RelayEvent
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_src_rpc_tsunagi_proto_init() }
func file_src_rpc_tsunagi_proto_init() {
	if File_src_rpc_tsunagi_proto != nil {
		return
	}
	file_src_rpc_tsunagi_proto_msgTypes[5].OneofWrappers = []any{
		(*ClientEvent_NoiseHandshake)(nil),
		(*ClientEvent_MessagePayload)(nil),
	}
	file_src_rpc_tsunagi_proto_msgTypes[6].OneofWrappers = []any{
		(*RelayEvent_NoiseHandshake)(nil),
		(*RelayEvent_MessagePayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_rpc_tsunagi_proto_rawDesc), len(file_src_rpc_tsunagi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_src_rpc_tsunagi_proto_goTypes,
		DependencyIndexes: file_src_rpc_tsunagi_proto_depIdxs,
		MessageInfos:      file_src_rpc_tsunagi_proto_msgTypes,
	}.Build()
	File_src_rpc_tsunagi_proto = out.File
	file_src_rpc_tsunagi_proto_goTypes = nil
	file_src_rpc_tsunagi_proto_depIdxs = nil
}
